name: Build knowledge from Excel

on:
  push:
    paths:
      - 'AnamnesisApp/AnamnesisApp/PTJDV.xlsx'
      - 'AnamnesisApp/AnamnesisApp/one_time_update.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AnamnesisApp/AnamnesisApp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas openpyxl

      - name: Generate JSONs from Excel
        run: python one_time_update.py

      - name: Commit & push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add knowledge.json video_links.json
          git commit -m "Auto-build knowledge/video links from Excel" || echo "No changes to commit"
          git push
