name: Build knowledge.json from Excel

on:
  push:
    paths:
      - 'AnamnesisApp/AAA.xlsx'
      - 'AnamnesisApp/one_time_update.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl
      - name: Run generator
        working-directory: AnamnesisApp
        run: python one_time_update.py
      - name: Commit JSONs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild knowledge.json & video_links.json from Excel"
          file_pattern: |
            AnamnesisApp/knowledge.json
            AnamnesisApp/video_links.json
