name: Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # להריץ כל 5 דקות 
  workflow_dispatch:        # מאפשר להריץ ידנית מה-Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping Streamlit app (HEAD)
        run: |
          curl -I -fsSL \
               -A "keepalive-bot" \
               --retry 3 --retry-delay 5 --retry-connrefused \
               --max-time 20 \
               https://anamnesisapp-vvmyqbozdxujidwflgxy4s.streamlit.app/ || true
